---
title: "p8105_hw5_yq2378"
author: "Qi Yumeng"
date: "2023-11-12"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```


```{r}
# loading data
homicide = read.csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

```{r}
homicide = homicide %>% 
  mutate(city_state = str_c(city, state, sep=", ")) 
ttl_bycity = homicide %>% 
  mutate(if_solved = if_else(disposition == "Closed by arrest",1,0 )) %>% 
  group_by(city) %>% summarise( ttl_cnt = n(), unsolved_cnt = n() - sum(if_solved), .groups = "keep") %>%
  arrange(desc(ttl_cnt)) 
ttl_bycity
```

For the city of Baltimore, MD, use the prop.test function to estimate the proportion of homicides that are unsolved; save the output of prop.test as an R object, apply the broom::tidy to this object and pull the estimated proportion and confidence intervals from the resulting tidy dataframe

```{r, Baltimore case}
ttl_cnt = 2827
unsolved_cnt = 1825
prop_output = prop.test(x = unsolved_cnt, n = ttl_cnt)
broom::tidy(prop_output)
broom::tidy(prop_output) %>% pull(estimate)
broom::tidy(prop_output) %>% pull(conf.low, conf.high)
```

```{r, iteration}
CI_bycity = 
  ttl_bycity |>
  mutate(prop_output = map2(.x = unsolved_cnt, .y = ttl_cnt, prop.test),
         prop_output = map(prop_output,broom::tidy)) |> 
  unnest(prop_output) |>
  mutate(CI = paste("(",round(conf.low,4),", ", round(conf.high,4),")"),
         estimate = round(estimate, 4)) |>
  select(city, ttl_cnt, unsolved_cnt, estimate,CI, conf.low, conf.high)
CI_bycity
```

```{r error_bar}
CI_bycity |>
  ggplot(aes(x = factor(city), y = estimate))+ 
  geom_point(size = 0.8) + 
  geom_errorbar(aes(ymin = conf.low,  ymax = conf.high), width = 0.2) + 
  coord_flip() + 
  theme_pubr() + xlab("City") + ylab("Estimate the Proportion of unsolved homicides") +
  theme(text = element_text(size = 8),
        plot.margin = unit(c(.1,.1,.1,.1),'cm'),
        legend.title = element_blank())

```
